name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/fast-note:todo-app-fe

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fast-note:todo-app-fe

      # Authenticate to Google Cloud
      - uses: google-github-actions/auth@v1
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      # SSH to the VM instance
      - uses: google-github-actions/ssh-compute@v1
        with:
          instance_name: instance-1
          region: asia-southeast1-b
          command: "sudo docker stop frontend"
          command: "sudo docker rm frontend"
          command: "sudo docker image rm khoitran990120/fast-note:todo-app-fe"
          command: "sudo docker run --name frontend --network todo-network -dp 3000:3000 khoitran990120/fast-note:todo-app-fe"
