name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/fast-note:todo-app-fe

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fast-note:todo-app-fe

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: '${{secrets.SA_EMAIL}}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'instance-1'
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY}}'
        run: sudo docker ps
      # - name: Run gg server
      #   run: gcloud compute ssh -t --zone "asia-southeast1-b" "instance-1" --project "fastnote-399603"

      # - run:
      # - run: sudo docker rm frontend
      # - run: sudo docker image rm khoitran990120/fast-note:todo-app-fe
      # - run: sudo docker run --name frontend --network todo-network -dp 3000:3000 khoitran990120/fast-note:todo-app-fe
